// <auto-generated />
using System;
using DataAccessLayer.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(CNCContext))]
    [Migration("20210109112840_removeFileAttr")]
    partial class removeFileAttr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Abstract.MiddleTables.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.RFQMiddles.RfqCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RFQId");

                    b.ToTable("RfqCertifications");
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.RFQMiddles.RfqMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RFQId");

                    b.ToTable("RfqMaterials");
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.RFQMiddles.RfqTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RFQId");

                    b.ToTable("RfqTechnologies");
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.RfqCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RfqCountries");
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.UserCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("CertificaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserCertifications");
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.UserIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserIndustries");
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.UserMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserMaterials");
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.UserTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserTechologies");
                });

            modelBuilder.Entity("Entities.Concrete.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("CertificateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("Entities.Concrete.CompanySize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("CountrySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CompanySizes");
                });

            modelBuilder.Entity("Entities.Concrete.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTINENT_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTRY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("COUNTRY_NUMBER")
                        .HasColumnType("int");

                    b.Property<string>("FULL_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISO3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Entities.Concrete.Iller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Plaka")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Illers");
                });

            modelBuilder.Entity("Entities.Concrete.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndustryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("Entities.Concrete.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Entities.Concrete.RFQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("BasicInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrespondenceLanguage")
                        .HasColumnType("int");

                    b.Property<string>("CustomRFQId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DelivaryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Diameter")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("MinTol")
                        .HasColumnType("int");

                    b.Property<int>("Need")
                        .HasColumnType("int");

                    b.Property<string>("OfferCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicationSettingsType")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RFQDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RFQ");
                });

            modelBuilder.Entity("Entities.Concrete.RfqFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RFQId");

                    b.ToTable("RfqFiles");
                });

            modelBuilder.Entity("Entities.Concrete.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AtModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TechnologyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.RFQMiddles.RfqCertification", b =>
                {
                    b.HasOne("Entities.Concrete.RFQ", "RFQ")
                        .WithMany("RfqCertifications")
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.RFQMiddles.RfqMaterial", b =>
                {
                    b.HasOne("Entities.Concrete.RFQ", "RFQ")
                        .WithMany("RfqMaterials")
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Abstract.MiddleTables.RFQMiddles.RfqTechnology", b =>
                {
                    b.HasOne("Entities.Concrete.RFQ", "RFQ")
                        .WithMany("RfqTechnologies")
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Concrete.RfqFile", b =>
                {
                    b.HasOne("Entities.Concrete.RFQ", null)
                        .WithMany("RfqFiles")
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
